### ISSUE TITLE
V1.4.1 does not recognize HackRF One - v1.4 works OK

### ISSUE THREAD

**Issue by bicurico** [pavsa/hackrf-spectrum-analyzer#12]
Hi,

I can run the previous version without problem (apart from the known freezes when frequency is changed).

But with the latest version, the HackRF One is not recognized.

Using Windows 10.

Regards,
Vitor

**Comment by pavsa** [comment]
Try to launch from command line to see if it reports any trace:
java -jar lib\hackrf_sweep_spectrum_analyzer.jar

**Comment by bicurico** [comment]
Hi,

Thanks for the reply.

This is what I get:

C:\Users\Vitor\Desktop>java -jar lib\hackrf_sweep_spectrum_analyzer.jar > error.log
Exception in thread "hackrf_sweep" java.lang.Error:

There is an incompatible JNA native library installed on this system
Expected: 5.2.0
Found:    4.0.1
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\RTLSDR Scanner;C:\Python27\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Vitor\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Aladdin\eToken\PKIClient\x32;C:\Program Files\Aladdin\eToken\PKIClient\x64;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\FileBot\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\Keysight\IO Libraries Suite\bin;C:\Program Files\IVI Foundation\VISA\Win64\ktvisa;C:\Program Files (x86)\Keysight\IO Libraries Suite\bin;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\ktvisa;C:\Program Files (x86)\IVI Foundation\IVI\bin;C:\Program Files\IVI Foundation\IVI\bin;C:\Program Files (x86)\IVI Foundation\VISA\winnt\agvisa;C:\Program Files\Portugal Identity Card;C:\Program Files\PothosSDR\bin;C:\Program Files\GNURadio-3.7\bin;C:\Users\Vitor\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Vitor\AppData\Local\Programs\Python\Python36\;C:\Users\Vitor\AppData\Local\Microsoft\WindowsApps;;..
To resolve this issue you may do one of the following:
- remove or uninstall the offending library
- set the system property jna.nosys=true
- set jna.boot.library.path to include the path to the version of the
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:199)
        at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
        at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.<clinit>(HackRFSweepNativeBridge.java:28)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:1249)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$6(HackRFSweepSpectrumAnalyzer.java:787)
        at java.lang.Thread.run(Unknown Source)

C:\Users\Vitor\Desktop>

I guess I need to upgrade Java?

I have a different question to you: I have written the “VMA Simple Spectrum Analyzer” software (VB .net) and I would love to be able to make a version for the HackRF One. Unfortunately the hackrf_sweep.exe hangs the device when using the “-1” option (single sweep).

If you are curious: https://vma-satellite.blogspot.pt/

I think you fixed that in your branch for the hackrf_sweep.dll. Is there a way I can either you your DLL in my VB .net project or could you tell me how to fix the hackrf_sweep.c source, so that the compiled output does work?

Unfortunately I am not literate in C++. I managed to compile the sources for the hackrf_tools (master branch), but that’s about it.

I will try to upgrade Java and report back.

Regards,
Vitor

**Comment by bicurico** [comment]
Just noticed it is not Java that is outdated, but JNA.

There is an incompatible JNA native library installed on this system
Expected: 5.2.0
Found:    4.0.1

No idea what to do…
Regards,
Vitor

**Comment by pavsa** [comment]
please go to lib\ dir first!
if it doesn't work, try to launch with these parameters:
java  -Djna.nosys=true -jar hackrf_sweep_spectrum_analyzer.jar

**Comment by bicurico** [comment]
Hi,

That worked.

C:\Users\Vitor\Desktop\lib>java -Djna.nosys=true -jar hackrf_sweep_spectrum_analyzer.jar
Persistent image set to 320x240
HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz
hackrf_sweep params:  freq 2400-2500MHz  FFTBin 100000Hz  samples 8192  lna: 40 vga: 0
call hackrf_sample_rate_set(20.000 MHz)
call hackrf_baseband_filter_bandwidth_set(15.000 MHz)
Sweeping from 2400 MHz to 2500 MHz
call hackrf_set_antenna_enable(0)
Stop with Ctrl-C
Persistent image set to 401x401
Persistent image set to 401x401
172 total sweeps completed, 80.94 sweeps/second
345 total sweeps completed, 81.18 sweeps/second
518 total sweeps completed, 81.27 sweeps/second
690 total sweeps completed, 81.24 sweeps/second
862 total sweeps completed, 81.27 sweeps/second

Exiting...
Total sweeps: 999 in 12.31224 seconds (81.27 sweeps/second)
hackrf_stop_rx() done
hackrf_close() done
hackrf_exit() done
fclose(fd) done
exit
HackRFSweep thread stopped.
Processing thread stopped.

C:\Users\Vitor\Desktop\lib>

Regards,
Vitor Martins-Augusto

**Comment by vsboost** [comment]
I am getting this with 1.4.2.

C:\Users\Me\Desktop\Radio & Phone\SDR\hackrf_sweep\lib>java -Djna.nosys=true -jar hackrf_sweep_spectrum_analyzer.jar
Persistent image set to 320x240
HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz
hackrf_sweep params:  freq 2400-2500MHz  FFTBin 100000Hz  samples 8192  lna: 40 vga: 0
Exception in thread "hackrf_sweep" java.lang.Error:

There is an incompatible JNA native library installed on this system
Expected: 5.2.0
Found:    5.1.0
(at C:\Users\Me\Desktop\Radio & Phone\SDR\hackrf_sweep\lib\.\win32-x86-64\jnidispatch.dll).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:199)
        at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
        at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.<clinit>(HackRFSweepNativeBridge.java:29)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:1249)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$6(HackRFSweepSpectrumAnalyzer.java:787)
        at java.lang.Thread.run(Unknown Source)
Persistent image set to 560x560
Persistent image set to 560x560
