### ISSUE TITLE
Doesn't recognise Hack RF after  changing to Win10

### ISSUE THREAD

**Issue by clarkerz** [pavsa/hackrf-spectrum-analyzer#18]
C:\Temp\hackrf_spectrum_analyzer\lib>java -jar hackrf_sweep_spectrum_analyzer.jar
Persistent image set to 320x240
HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz
hackrf_sweep params:  freq 2400-2500MHz  FFTBin 100000Hz  samples 8192  lna: 40 vga: 0
Persistent image set to 261x261
Exception in thread "hackrf_sweep" java.lang.UnsatisfiedLinkError: Unable to load library 'hackrf-sweep': Native library (win32-x86/hackrf-sweep.dll) not found in resource path ([rsrc:./, jar:rsrc:miglayout15-swing.jar!/, jar:rsrc:jcommon-1.0.17.jar!/, jar:rsrc:jfreechart-1.0.14.jar!/, jar:rsrc:hackrf-sweep-jna.jar!/, jar:rsrc:jna-4.5.1.jar!/])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:369)
        at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.<clinit>(HackRFSweepNativeBridge.java:30)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:1249)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$6(HackRFSweepSpectrumAnalyzer.java:787)
        at java.lang.Thread.run(Unknown Source)

**Comment by clarkerz** [comment]
> C:\Temp\hackrf_spectrum_analyzer\lib>java -jar hackrf_sweep_spectrum_analyzer.jar
> Persistent image set to 320x240
> HackRFSweep thread stopped.
> Starting hackrf_sweep... 2400-2500MHz
> hackrf_sweep params: freq 2400-2500MHz FFTBin 100000Hz samples 8192 lna: 40 vga: 0
> Persistent image set to 261x261
> Exception in thread "hackrf_sweep" java.lang.UnsatisfiedLinkError: Unable to load library 'hackrf-sweep': Native library (win32-x86/hackrf-sweep.dll) not found in resource path ([rsrc:./, jar:rsrc:miglayout15-swing.jar!/, jar:rsrc:jcommon-1.0.17.jar!/, jar:rsrc:jfreechart-1.0.14.jar!/, jar:rsrc:hackrf-sweep-jna.jar!/, jar:rsrc:jna-4.5.1.jar!/])
> at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
> at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
> at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:369)
> at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.(HackRFSweepNativeBridge.java:30)
> at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:1249)
> at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$6(HackRFSweepSpectrumAnalyzer.java:787)
> at java.lang.Thread.run(Unknown Source)

Doh!! Missing from my path..fixed this.

**Comment by clarkerz** [comment]
No it didn't...Still throwing the same error..

**Comment by clarkerz** [comment]
I have definitely fixed this now. When I installed Java on the fresh windows 10 install, it installed the latest 1.8.0_201 however when I uninstalled and then installed 1.8.0_171 then the error goes away and I can also now launch the exe rather than the jar file directly! :)

**Comment by pavsa** [comment]
You need install 64bit java, not 32bit. It's written in requirements on the main page:
**Install Java JRE 64bit v1.8+**

You can see it trying to load 32bit lib:
Native library (**win32-x86**/hackrf-sweep.dll) 

If it was loading 64bit and not working, it would look like this:
Native library (**win32-x86-64**/hackrf-sweep.dll)

**Comment by clarkerz** [comment]
Doh!! Schoolboy error....Not sure why the default install did that but I have reinstalled manually and it does now work. Thanks
