### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by christianhenriksen** [pavsa/hackrf-spectrum-analyzer#6]
Hi,
is there any chance you could create a howto for building this project in eclipse?
I have installed Eclipse and imported hackrf-spectrum-analyser, but I get many many errors in the project, so I suspect I am doing something wrong.

Thanks for the software, its great.

**Comment by christianhenriksen** [comment]
I was actually able to make the software run now through eclipse! I have one exeption thrown:

To make it all work, I had to install the full version of eclipse, and then import the project from git. 
Very exiting now if I can fix this last issue.

HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz 
hackrf_sweep params:  freq 2400-2500MHz  samples 8192  lna: 40 vga: 0
Exception in thread "hackrf_sweep" java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path ([file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/bin/, file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/miglayout15-swing.jar, file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/lib/jcommon-1.0.17.jar, file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/lib/jfreechart-1.0.14.jar, file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/lib/hackrf-sweep-jna.jar, file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/lib/jna/jna-min-4.3.0.jar, file:/C:/Users/christian/Desktop/eclipse/configuration/org.eclipse.osgi/977/0/.cp/jacocoagent.jar])
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:921)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:881)
	at com.sun.jna.Native.<clinit>(Native.java:156)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
	at jspectrumanalyzer.nativebridge.HackRFSweepNativeBridge.<clinit>(HackRFSweepNativeBridge.java:29)
	at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:841)
	at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.access$9(HackRFSweepSpectrumAnalyzer.java:818)
	at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer$11.run(HackRFSweepSpectrumAnalyzer.java:735)
	at java.lang.Thread.run(Unknown Source)

**Comment by pavsa** [comment]
Get the release zip and copy lib/win32-x86-64 folder to the project and make sure the working directory where you launch the application is the root of your project so that JNA can load the shared libraries from ./win32-x86-64/

I have to clean up the way it is compiled.

**Comment by christianhenriksen** [comment]
Thanks a lot. I have it working running through eclipse now, and its scanning :-D

**Comment by pavsa** [comment]
no problem :)

**Comment by OneTheLastRF** [comment]
Hi, 
I couldn't find file:/C:/Users/christian/git/hackrf-spectrum-analyzer/src/hackrf-sweep/lib/hackrf-sweep-jna.jar file under the lib file.
Please help me,
