### ISSUE TITLE
HackRF not found by hackrf-spectrum-analyzer under Win11 ? JVMCFRE199E bad major version 55.0

### ISSUE THREAD

**Issue by aneitzel** [pavsa/hackrf-spectrum-analyzer#63]
Hello, 

HackRF (with portapack, latest firmware 2023.01.1 installed), running fine under Win11 in SDR++ and other SDR tools. Unfortunately i dont got it managed to run with hackrf-spectrum-analyzer. It will always show "HackRF not connected" ???
I noticed a message during startup, details see below:

**Exception in thread "hackrf_sweep" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 55.0 of class=hackrfsweep/HackrfSweepLibrary$hackrf_sweep_lib_start__fft_power_callback_callback, the maximum supported major version is 52.0; offset=6**

Any idea whats wrong here?

----------------------------------------------------
HackRFinfo output:

hackrf_info version: 2023.01.1
libhackrf version: 2023.01.1 (0.8)
Found HackRF
Index: 0
Serial number: 0000000000000000f77c60dc261b78c3
Board ID Number: 2 (HackRF One)
Firmware Version: n_240430 (API:1.08)
Part ID Number: 0xa000cb3c 0x006a4358
Hardware Revision: older than r6
Hardware supported by installed firmware:
    HackRF One

----------------------------------------------------

hackrf_sweep_spectrum_analyzer_windows.cmd

C:\Users\Username\Downloads\HackRF Spectrum Analyzer>java -Djna.platform.library.path=lib\win32-x86-64 -jar lib\hackrf_sweep_spectrum_analyzer.jar
Persistent image set to 320x240
HackRFSweep thread stopped.
Starting hackrf_sweep... 2400-2500MHz
hackrf_sweep params:  freq 2400-2500MHz  FFTBin 100000Hz  samples 8192  lna: 40 vga: 0 antenna_lna: false
Exception in thread "hackrf_sweep" java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 55.0 of class=hackrfsweep/HackrfSweepLibrary$hackrf_sweep_lib_start__fft_power_callback_callback, the maximum supported major version is 52.0; offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
        at java.security.AccessController.doPrivileged(AccessController.java:782)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:902)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:885)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.sweep(HackRFSweepSpectrumAnalyzer.java:1237)
        at jspectrumanalyzer.HackRFSweepSpectrumAnalyzer.lambda$6(HackRFSweepSpectrumAnalyzer.java:774)
        at java.lang.Thread.run(Thread.java:826)
Persistent image set to 401x401
Persistent image set to 401x401

**Comment by dave3825us** [comment]
Anything going on with this program? Wont connect to hackrf win 10
